Add compatibility check for WordPress 5.0 or Gutenberg.
getblocklab/block-lab pull request #182
Opened 2018-12-02 17:30 UTC by kopepasah

This pull request adds a compatibility check for WordPress 5.0 or Gutenberg plugin.

2018-12-02 17:33 UTC, kopepasah commented
Will close #168

2018-12-02 22:27 UTC, lukecarbis requested changes

2018-12-02 22:27 UTC, lukecarbis commented on block-lab.php
> +	return __( 'Block Lab plugin error: Your version of WordPress is too old or Gutenberg Plugin is not installed. You must be running WordPress 5.0 or install the Gutenberg Plugin to use Block Labs.',
"… or _the_ Gutenberg Plugin is not installed"

2018-12-02 22:27 UTC, lukecarbis commented on block-lab.php
> +	return __( 'Block Lab plugin error: Your version of WordPress is too old or Gutenberg Plugin is not installed. You must be running WordPress 5.0 or install the Gutenberg Plugin to use Block Labs.',
Block Lab (not Block Labs)

2018-12-02 22:43 UTC, kopepasah commented on block-lab.php
> +	return __( 'Block Lab plugin error: Your version of WordPress is too old or Gutenberg Plugin is not installed. You must be running WordPress 5.0 or install the Gutenberg Plugin to use Block Labs.',
Fixed

2018-12-03 01:40 UTC, lukecarbis approved these changes

2018-12-03 01:40 UTC, merged