Remove duplicate id from field description
getblocklab/block-lab pull request #345
Opened 2019-06-18 11:40 UTC by mukeshpanchal27

**Steps to replicate issue**

1. Admin Panel > Block Lab > Add New
2. Add new field type as per your need
3. Add another new field type as per your need

**Issue**

Each new field generate new Field Label and Field Name field with duplicate id of "block-fields-edit-label-description" and "block-fields-edit-name-description"

2019-06-18 20:57 UTC, lukecarbis requested changes
Great pickup @mukeshpanchal27 .

I don't think these ID's are actually used by anything – maybe it would be better to simply remove the ID attribute altogether?

There's also `block-properties-keywords-description` on line 402, and `block-properties-keywords-description` on line 473. Obviously the first one is wrong, but I think we can remove the IDs from both.

2019-06-19 05:12 UTC, mukeshpanchal27 commented
@lukecarbis updated PR with remove ids attributes which will duplicated when we add new fields from admin panel

2019-06-19 05:44 UTC, lukecarbis approved these changes

2019-06-19 05:45 UTC, lukecarbis commented
Thanks heaps @mukeshpanchal27 !

2019-06-19 05:45 UTC, merged