Add a migration submenu page
getblocklab/block-lab pull request #629
Opened 2020-06-24 20:47 UTC by kienstra

#### Changes
* Adds a 'Migration' submenu under `/wp-admin > 'Block Lab'`
* Adds Rob's CSS from the Gist
* Adds an empty script to populate with the JS for migration

#### Testing instructions

2020-06-30 19:45 UTC, kienstra commented
There's a lot of work left here, but there's now a 'Migrate' submenu page:

<img width="583" alt="migration-ui-here" src="https://user-images.githubusercontent.com/4063887/86170173-56cdf400-bae0-11ea-842b-40aceecc7b5d.png">

2020-06-30 19:50 UTC, kienstra commented
If it's alright, I think React will be useful here, and I started the React setup for the Migrate page.

It'd be possible to do this in Vanilla JS, like how the CPT page is now.

But I think I'll be slower to develop this, mixing JavaScript and PHP. And with React, it'll be much easier to test.

2020-07-01 21:55 UTC, kienstra commented
There's still a lot of work left, but here's what the migration looks like right now. Only 2 of the 5 steps are in place so far.

![migration-for-now](https://user-images.githubusercontent.com/4063887/86295119-856ccd00-bbbb-11ea-88e7-707dea648f1b.gif)

2020-07-02 20:55 UTC, lukecarbis commented
Looking _amazing_, Ryan! 🤩

2020-07-02 21:09 UTC, kienstra commented
Thanks, Luke! Thanks for your great work on the UI.

2020-07-07 19:52 UTC, kienstra commented
There's still a lot of work left, but here's what it looks like now:

![basic-bl-migration](https://user-images.githubusercontent.com/4063887/86835080-3ca49080-c061-11ea-975e-be009e41a006.gif)

2020-07-07 21:05 UTC, lukecarbis commented
Looking good Ryan! I'm sure @RobStino will drop in with a few design tweaks at some stage, too.

Interesting point on onboarding. Do you think we should somehow try to disable it for migrations? IMO, it's not a huge problem, so if it's going to cause a bunch of extra work, I wouldn't worry about it.

2020-07-08 00:28 UTC, kienstra commented
Ah, good point about the onboarding. I'll look at if there's a query var I could use to disable the onboarding for the migration.

2020-07-08 01:12 UTC, lukecarbis commented
Only if it's easy.

On Wed, 8 Jul 2020 at 10:28, Ryan Kienstra <notifications@github.com> wrote:

> Ah, good point about the onboarding. I'll look at if there's a query var I
> could use to disable the onboarding after the migration.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/getblocklab/block-lab/pull/629#issuecomment-655209188>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIL7Q255JLWINXW7JIUSCDR2O4SNANCNFSM4OHIYMMQ>
> .
>

2020-07-08 01:24 UTC, kienstra commented
OK, thanks.

2020-07-09 01:42 UTC, kienstra commented
## Doesn't work yet

* Submitting the Genesis Pro license key:

![license-g-pro](https://user-images.githubusercontent.com/4063887/86987247-34308080-c15b-11ea-9f7c-8a47da473d2f.png)

* Automatically downloading GCB:

![migrates-block](https://user-images.githubusercontent.com/4063887/86987333-6cd05a00-c15b-11ea-8b22-e188b7765c2a.png)

## Does work
* The migration workflow, including migrating the `block_lab` CPT and the blocks in the `post_content`

2020-07-09 01:44 UTC, kienstra commented
To test this, please also clone [GCB](https://github.com/studiopress/genesis-custom-blocks) and do `composer install && npm install && npm run build`. This is so that it can be activated in the last step of the UI.

To reverse the migration:
```sh
wp shell
( new Block_Lab\Blocks\Migration\Post_Content( 'genesis-custom-blocks', 'block-lab' ) )->migrate_all();
( new Block_Lab\Blocks\Migration\Post_Type( 'genesis_custom_block', 'genesis-custom-blocks', 'genesis_custom_blocks', 'block_lab', 'block-lab', 'block_lab' ) )->migrate_all();

```

2020-07-09 21:55 UTC, kienstra commented
What do you think about the messages on submitting the Genesis Pro subscription key?

![feedback-saved-message](https://user-images.githubusercontent.com/4063887/87094607-c6d92a00-c204-11ea-928d-5ebc0c96f101.gif)

There's no validation of the key, it just checks that it's a non-empty string.

As you know, the validation logic is in Genesis Custom Blocks.

There's also a message if `update_option()` returns `false`:

>There was an error saving the key

2020-07-10 21:25 UTC, johnstonphilip commented
Hey @kienstra - I took this for a spin and this works really well and looks great!

I hit a couple snags, though may not be related. 

1. I attempted to have both plugins active at the same time, which is throwing this:

```
Plugin could not be activated because it triggered a fatal error.


Fatal error: Cannot redeclare block_field() (previously declared in /Users/phil.johnston/Documents/wps/wpengine1/app/public/wp-content/plugins/block-lab/php/helpers.php:20) in /Users/phil.johnston/Documents/wps/wpengine1/app/public/wp-content/plugins/genesis-custom-blocks/php/Helpers.php on line 20

```

2. The "Developer Notice button didn't seem to work (nothing happens upon click)

2020-07-10 21:35 UTC, kienstra commented
Hi @johnstonphilip,
Thanks a lot for testing this, I really appreciate it.

Yeah, I still need to fix this issue with both plugins being active.

https://github.com/getblocklab/block-lab/pull/629/commits/8f74facec192cb782ac82aac568b1f3141baa3a0#diff-1f12e601c690bb1256c9c71f5989a088R39 adds a link for the developer notice.

Thanks, and have a great weekend!

2020-07-10 22:45 UTC, kienstra commented on js/migration/components/steps/get-genesis-pro.js
> +	const urlGetGenesisPro = 'https://my.wpengine.com/signup?plan=genesis-pro';
Is this a stable URL? Or should it be changed to https://www.studiopress.com/genesis-pro/ ?

2020-07-10 23:12 UTC, kienstra commented on js/migration/components/steps/get-genesis-pro.js
> +	const urlGetGenesisPro = 'https://my.wpengine.com/signup?plan=genesis-pro';
Is this a stable URL? Or should it be changed to https://www.studiopress.com/genesis-pro/ ?

2020-07-10 23:36 UTC, kienstra commented
### Request for review

Hi @lukecarbis and @RobStino,
Could you please review this? The [top comment](https://github.com/getblocklab/block-lab/pull/629#issue-439492116) is up to date.

This migration doesn't actually install Genesis Custom Blocks. That's in a ticket that's scheduled for next sprint, though I'll look at doing that earlier than planned.

Here are example error messages from post content migration:

<img width="767" alt="migration-errors-here" src="https://user-images.githubusercontent.com/4063887/87210480-45a09680-c2db-11ea-9f04-237daa1c99a5.png">

Though ideally there won't be errors 😄 

There are also `@todo` comments here to add URLs, like the [Developer Notice](https://github.com/getblocklab/block-lab/pull/629/files#diff-1f12e601c690bb1256c9c71f5989a088R20). Once we know those, I'll add them in.

It'll be interesting how long the post content migration takes for you. It usually takes a few seconds for me.

Thanks, Rob and Luke!

2020-07-13 04:05 UTC, lukecarbis requested changes
All the code looks fantastic, of course.

I'm not seeing any migration menu in Block Lab though.
https://ufile.io/1n084xcy

2020-07-13 04:05 UTC, lukecarbis commented on js/migration/components/steps/get-genesis-pro.js
> +	const urlGetGenesisPro = 'https://my.wpengine.com/signup?plan=genesis-pro';
In this case, sending people directly to the signup page (not another marketing page) is preferred, so leave as is.

2020-07-13 04:05 UTC, lukecarbis commented on js/migration/components/steps/get-genesis-pro.js
> +			setSubmissionMessage( __( "That looks like your coupon code. Please click 'Get Genesis Pro' and enter your coupon code there.", 'block-lab' ) );
Very, very, very nice. Brilliant work.

2020-07-13 04:09 UTC, kienstra commented on js/migration/components/steps/get-genesis-pro.js
> +			setSubmissionMessage( __( "That looks like your coupon code. Please click 'Get Genesis Pro' and enter your coupon code there.", 'block-lab' ) );
Thanks, Luke!

2020-07-13 04:14 UTC, kienstra commented
Hi @lukecarbis,
Sorry the menu's not displaying. That makes it hard to test 😆 

Does this help?

```diff
diff --git a/php/admin/migration/class-submenu.php b/php/admin/migration/class-submenu.php
index d953c8e..4d1b1a7 100644
--- a/php/admin/migration/class-submenu.php
+++ b/php/admin/migration/class-submenu.php
@@ -135,7 +135,7 @@ class Submenu extends Component_Abstract {
         * @return bool Whether the user can view the migration page.
         */
        public function user_can_view_migration_page() {
-               return current_user_can( 'install_plugins' ) && current_user_can( self::MIGRATION_CAPABILITY );
+               return true;
        }
```

...just to narrow down the problem.

2020-07-13 04:20 UTC, lukecarbis commented
Ah, damn. Sorry man. Had the wrong branch checked out.

2020-07-13 04:21 UTC, kienstra commented
All good, there's a lot to juggle here with 2 plugins and all of the setup instructions.

2020-07-13 04:46 UTC, lukecarbis requested changes
<img width="1121" alt="Screen Shot 2020-07-13 at 2 22 29 pm" src="https://user-images.githubusercontent.com/1097667/87271570-ec24ab80-c516-11ea-85f2-f5b1fbf3608b.png">
The last paragraph should have no bottom margin.

<img width="1129" alt="Screen Shot 2020-07-13 at 2 34 44 pm" src="https://user-images.githubusercontent.com/1097667/87271584-fba3f480-c516-11ea-9d41-3e6e55448900.png">
Made a bunch of changes to this section. @RobStino could you please review?

<img width="611" alt="Screen Shot 2020-07-13 at 2 39 38 pm" src="https://user-images.githubusercontent.com/1097667/87271598-078fb680-c517-11ea-8f8c-3174c1d0ac13.png">
Is this button supposed to work yet?

<img width="501" alt="Screen Shot 2020-07-13 at 2 40 59 pm" src="https://user-images.githubusercontent.com/1097667/87271603-0e1e2e00-c517-11ea-973f-5cc54e92cd78.png">
Not yet responsive.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1097667/87271700-63f2d600-c517-11ea-9393-3c875bb934a0.gif)
Animations between steps are very quick / disorienting.

(happened to fast for a screenshot)
The loading bar during migration seemed blue instead of purple.

2020-07-13 04:47 UTC, lukecarbis commented
Maybe instead of a loading bar we should show a spinner, since it's all happening awfully fast. Maybe it's only happening fast because we're doing it locally?

2020-07-13 04:54 UTC, kienstra commented
>Is this button supposed to work yet?

Yeah, the 'Submit' button for the license should work. Is there a console error?

2020-07-13 04:56 UTC, kienstra commented
>Maybe instead of a loading bar we should show a spinner, since it's all happening awfully fast. Maybe it's only happening fast because we're doing it locally?

Yeah, a spinner might be a good idea. Some steps will probably be really fast, especially the CPT migration. In my local, it almost was too fast to see.

Yeah, maybe the speed is from being in a local environment, but some calls will probably be fast normally. Like the CPT conversion.

2020-07-13 05:09 UTC, lukecarbis commented
I just tried saving the key again and it worked. Must have broken when I messed with the DOM for that mockup. My bad, sorry.

2020-07-13 05:10 UTC, kienstra commented
No problem, it could have been a bug, who knows 😄

2020-07-14 02:51 UTC, RobStino reviewed
Hey @kienstra 
This is looking really good.
I tested both without and with a Block Lab Pro license key active and got expected behaviour.
The only thing that I spotted that might be weird is that I got this error in the block editor _after_ the migration.
![image](https://user-images.githubusercontent.com/1578148/87378015-403f9680-c5d0-11ea-9ee5-fdd82619bec7.png)
Now I know that the GCB plugin wasn't installed as that part is yet to be sorted, but as the block had been migrated, I was unsure about seeing the `block-lab` slug in that error notice. Not sure how it works technically, or even if this is an issue, but wanted to call it out just in case.

There are a couple of things that need adjusting:
1. We need a better disabled-state for the buttons. They still look active.
2. The animation between steps is janky. I think that is my hacky CSS (height transitions in CSS are notoriously hard!). Is there something you could do with JS to handle transitions?
3. We should capture a task somewhere to update all the external links before launch.

2020-07-14 02:56 UTC, RobStino commented
For the disabled state button (#3 above), I mean the next-step buttons and their state prior to the checkbox being checked.
Here is some CSS that I think styles it appropriately:
`  color: var(--color-gray-500);
    background-color: var(--color-gray-200);
    box-shadow: none;
    cursor: not-allowed;`
for the "allowed state", we'll probably have to add:
`cursor: pointer;`

2020-07-14 03:13 UTC, kienstra commented
Hi @RobStino,
Thanks for testing this and your comments.

>The only thing that I spotted that might be weird is that I got this error in the block editor after the migration.

>...I was unsure about seeing the block-lab slug in that error notice. 

Right, that shouldn't happen. The migration should have changed that from `block-lab/notice` to `genesis-custom-blocks/notice`.

What post type was that block in? A post, page, etc..?

2020-07-14 09:00 UTC, nickcernis commented
Hey, @kienstra. The migration works smoothly for me and looks great. Nice work!

A couple of things I dug up:

### Restoring from browser backups of an unsaved post breaks blocks

The only way I found of reproducing the “your site doesn't include support for the [blockname] block“ from [Rob's comment](https://github.com/getblocklab/block-lab/pull/629#pullrequestreview-447748164) was to restore an old browser save or autosave after doing the migration:

1. Add a custom block to a page and publish the page.
2. Add another custom block to the page, do not publish the page, and wait ~10 seconds for the browser to back up your changes to local storage.
2. Refresh the page. You should see “The backup of this post in your browser is different from the version below.” and a button to “Restore the backup”.
3. In a new tab, complete the block migration.
4. Return to the page (refresh again if you wish) and click “Restore the backup”.

The migrated block and the unsaved block will be replaced with the old cached blocks, because the backup was made with the old Block Lab block names.

This might not be something you need/want to account for, but just flagging it as a possibility in case it comes up in support.

I would expect to see a similar issue with any post autosaves (“There is an autosave of this post that is more recent than the version below. View the autosave.”) but that requires a manual compare-and-restore step where it's more obvious that the block names have changed because you get to see the diff first.

### Keyboard and screen reader accessibility

I did a basic test for keyboard and screenreader accessibility. These may be separate issues to follow up on:

1. Navigating the page at `wp-admin/edit.php?post_type=block_lab&page=block-lab-migration` by keyboard (in Chrome, click to focus the page, then repeatedly press tab) reveals hidden next steps before I have begun the first step. I would not expect to be able to access later steps until I have completed the first one. It could prove confusing for a screen reader user or someone whose only means of access is by keyboard.

    ![tab-through-steps](https://user-images.githubusercontent.com/647669/87402367-bede0900-c5bb-11ea-8139-ff0b2de4ca8d.gif)

2. Step 2: the “ More details here” links could be more descriptive so that screenreader users know what they're clicking on. https://www.washington.edu/accessibility/links/.

3. There's no audible progress alert for screen reader users. When I click “migrate now” in step 3 I would not be able to tell that the step has ever completed if I can't see the screen. In Genesis, John solved this with `wp.a11y.speak()` calls to announce what's going on:
    - [wp-a11y-speak](https://make.wordpress.org/accessibility/handbook/markup/wp-a11y-speak/)
    - [Genesis a11y.speak source](https://github.com/studiopress/genesis/blob/75377bc8f28004454932c5cdf3733862a74029ec/lib/js/admin.js#L359)

4. The “…and step into the FUTURE ꜰᴜᴛᴜʀᴇ FUTURE.” text in step 4 is cute, but VoiceOver read this as, “and step into the future latin letter small capital f, latin letter small capital u, latin letter small capital t, latin letter small capital u, latin letter small capital r, latin letter small capital e future”, which might annoy screenreader users.

   I would either wrap the tags in spans and user CSS to adjust their size (which VoiceOver will read as “step into the future future future”) or just change it to “…and step into the future”, even if it loses some of the personality you were going for here.

    It's not so bad in this case but it's something to be aware of as it can get much worse! https://twitter.com/kentcdodds/status/1083073242330361856

2020-07-14 16:11 UTC, kienstra commented
Hi @nickcernis,
Thanks so much for your detailed testing. Great idea to do accessibility testing, I really appreciate it.

I'll work on applying your points.

2020-07-14 17:49 UTC, kienstra commented
Hi @lukecarbis and @RobStino,
How does this look for the 'Get Genesis Pro' step?

It applies Luke's suggestions from https://github.com/getblocklab/block-lab/pull/629#pullrequestreview-446978121.

Though it's not responsive.

![to-g-pro](https://user-images.githubusercontent.com/4063887/87458863-361d9800-c5d0-11ea-9583-0d3ffe992cd3.png)

2020-07-14 18:17 UTC, kienstra commented
Also, what do you think about this use of a spinner instead of the `<progress>` bar?

The progress bar was good, but a lot of the time ended up being on the post content migration. The CPT migration was too fast to see in my local.

![spinner-here](https://user-images.githubusercontent.com/4063887/87461550-37e95a80-c5d4-11ea-8f27-6d0165ee6ea0.gif)

2020-07-14 19:26 UTC, kienstra commented
Changing steps is now a little smoother:

![chaning-steps](https://user-images.githubusercontent.com/4063887/87467499-abdc3080-c5dd-11ea-9c67-63cc9fd008d8.gif)

This [transitions the max-height](https://css-tricks.com/using-css-transitions-auto-dimensions/#technique-1-max-height).

It's hard to transition from a defined height to `height: auto;`. This is essentially a hack to transition the max-height.

An alternative would be a [more complex JS solution](https://css-tricks.com/using-css-transitions-auto-dimensions/#technique-3-javascript)

2020-07-14 19:57 UTC, kienstra commented
This step is more responsive now:

![them-tiles](https://user-images.githubusercontent.com/4063887/87470372-48a0cd00-c5e2-11ea-8bf9-899306e9f388.gif)

2020-07-14 21:01 UTC, kienstra commented
>3. We should capture a task somewhere to update all the external links before launch.

Sure, I opened BH-452 for that.

2020-07-15 03:27 UTC, kienstra commented
This is ready for another review.

2020-07-15 03:52 UTC, RobStino commented
Hey @kienstra ,
Thanks for all those edits. This looks good to me.
I feel like I might want to tweak a few things around padding and transition durations. I'll work on a separate PR for these though. That would be the best approach hey?

2020-07-15 13:49 UTC, nickcernis commented
Accessibility is much better now. Nice job!

2020-07-15 14:36 UTC, kienstra commented
Hi @RobStino,
Thanks a lot for looking at this.

>I feel like I might want to tweak a few things around padding and transition durations. I'll work on a separate PR for these though. That would be the best approach hey?

Sure, that sounds good. A PR to the `add/full-migration` branch would be great.

2020-07-15 14:41 UTC, kienstra commented
Hi @nickcernis,
Thanks a lot for your detailed review. Sorry for not responding to you about [your suggestions](https://github.com/getblocklab/block-lab/pull/629#issuecomment-658062873).

Great point about restoring from browser backups. Thanks for your steps to reproduce, I also saw that.

Of your 5 suggestions on accessibility, I applied all of them except 5:

>The final “activate plugin” step redirects to the plugin page, where it's not clear what has happened as a screen reader user. If you can activate the plugin (and announce “Genesis Custom Blocks plugin activated” or similar) but stay on the migration page that may be less disorientating.

It's a really good suggestion. But due to a quirk in how Genesis Custom Blocks and Block Lab have some of the same functions, they can't be active at the same time. So as part of activating GBC, it has to activate Block Lab.

Thanks for your great suggestions.

2020-07-16 16:34 UTC, mindctrl commented
"Backup your site" should probably be "Back up your site"... backup is a noun.

2020-07-16 16:36 UTC, kienstra commented
Ah, good point!

2020-07-16 16:51 UTC, kienstra commented
'backup' is now changed to 'back up':

![back-up-site](https://user-images.githubusercontent.com/4063887/87699513-94768200-c75a-11ea-9d13-1d790e8a7006.png)

2020-07-16 22:09 UTC, lukecarbis approved these changes
@kienstra 

Spinner looks great.

Can we change "Save your Genesis Pro Key / Submit" to "Paste your Genesis Pro Key / Save"

Like @RobStino suggested, I have a few animation / design tweaks in mind, but happy to move them to a separate PR.

2020-07-16 22:09 UTC, lukecarbis commented
Feel free to merge with or without the suggested copy change.

2020-07-17 02:18 UTC, kienstra commented
Hi @lukecarbis,
Thanks, good idea!

It's now changed to 'Paste your...' and 'Save':

![paste-save-here](https://user-images.githubusercontent.com/4063887/87741338-e4c90080-c7a9-11ea-81a0-597144cd59d3.png)

2020-07-17 02:33 UTC, merged

2020-07-28 20:33 UTC, sleepykate commented on js/migration/components/intro.js
> +					{ __( 'Genesis Custom Blocks is now the home of all our custom block efforts and what we have planned is very very cool!', 'block-lab' ) }
Optional polish: Change "very very" to "very, very"

2020-07-28 20:40 UTC, sleepykate commented
Optional polish:

- Change "ok" to "okay" throughout
- Change "&" to "and" throughout
- Do a quick pass on headers and CTAs for consistent capitalization (sentence case vs. title case)

2020-07-28 21:16 UTC, kienstra commented
Thanks, @sleepykate! Good ideas.

2020-07-28 21:17 UTC, kienstra commented
@RobStino and @lukecarbis,
What do you think about [those suggestions](https://github.com/getblocklab/block-lab/pull/629#issuecomment-665271278)? 

I could apply them today.

Thanks!

2020-07-28 21:35 UTC, lukecarbis commented
@sleepykate Thanks for these suggestions!

Personally I always prefer `okay` to `ok`, too. However, WordPress tends to go with OK (capitalised) ([examples here](https://translate.wordpress.org/projects/wp/dev/en-au/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=988&filters%5Btranslation_id%5D=2986019)).

On the other hand… all those `OK` instances are button actions, but ours are in the middle of sentences. Given this, I'd prefer to go with Katie's suggestion and **change them to `okay`**.

Regarding the ampersand, my opinion is that ampersands are good in headers, but not body text. So keep "Update Hooks & API" but change lines where ampersands are used in that way.

2020-07-28 21:50 UTC, kienstra commented
Thanks, @lukecarbis! I'll push those changes to https://github.com/getblocklab/block-lab/pull/660.