Add handling for the Pro plugin
getblocklab/block-lab pull request #688
Opened 2020-08-26 08:02 UTC by kienstra

#### Changes
* On entering a valid subscription key, this downloads the Pro plugin, not the free one.

#### Testing instructions
1. Ensure there is a valid Block Lab Pro subscription key saved
2. Go to `/wp-admin` > Migrate 
3. Enter a valid Genesis Pro subscription key
4. Expected: there's a message 'Thanks, the key is valid':

<img width="935" alt="key-is-valid" src="https://user-images.githubusercontent.com/4063887/91277262-33be6a00-e748-11ea-8d6e-eedeeb724862.png">

5. Do `wp transient get genesis_custom_blocks_pro_download_link`
6. Expected: this should be an s3 URL, though it won't be an actual `.zip` file yet

2020-08-26 08:06 UTC, kienstra commented on php/admin/migration/class-api.php
> -	public function register_route_update_subscription_key() {
Just moved to the class `Subscription_Api`

2020-08-26 08:41 UTC, kienstra commented
Hi @lukecarbis,
Could you please review this? 

On entering a Genesis Pro key, it validates it, and gets the download link for GCB Pro.

Then, it uses that download link to install that plugin.

Also, should I remove this?

<img width="795" alt="genesis-pro-copy" src="https://user-images.githubusercontent.com/4063887/91281633-f230bd80-e74d-11ea-9010-81a0c211d3ad.png">

Thanks, Luke!

2020-08-27 02:29 UTC, lukecarbis commented
Awesome, Ryan! Couple of things:

1. There should be a spinner when the user clicks "Save" to indicate that the save process is happening.
2. The Save button should have a `:hover` and `:active` state, like other buttons. Something like:
```css
color: var(--color-purple-800);
background-color: var(--color-purple-300);
```
3. Let's remove the coupon code generation process. We're not doing that anymore.
4. Let's change the text etc. as follows:
<img width="1132" alt="Screen Shot 2020-08-27 at 12 27 29 pm" src="https://user-images.githubusercontent.com/1097667/91376576-b89ca700-e860-11ea-9385-3bc5787b5843.png">

> Since you're a Block Lab Pro customer, we've already emailed you regarding setting up a WP Engine account with a free Pro subscription.
>
> To migrate and maintain your Block Lab Pro feature set with Genesis Custom Blocks, you will need your Genesis Pro subscription key.
>
> - Already have got it? Enter the subscription key below to continue migrating.
> - Don’t have one yet? Please opt-in using the link below.
>
> [Opt-in for Genesis Pro] (This may take up to 3 working days)

The button should link to: https://forms.gle/26u7NDRUp2A9i2aF8

2020-08-27 02:34 UTC, lukecarbis requested changes

2020-08-27 02:34 UTC, lukecarbis commented on js/migration/components/steps/get-genesis-pro.js
> +			const errorMessage = error.message ? error.message : __( 'There was an error in validating the key.', 'block-lab' );
```suggestion
			const errorMessage = error.message ? error.message : __( 'There was an error validating the key.', 'block-lab' );
```

2020-08-27 02:34 UTC, lukecarbis commented on js/migration/components/steps/test/get-genesis-pro.js
> +	getByText( 'Thanks, the key is valid.' );
```suggestion
	getByText( 'Thanks! Your key is valid, and has been saved.' );
```

2020-08-27 02:42 UTC, lukecarbis commented
BTW, the I did get a download link in the transient, but the download didn't work. The download link looked like: `https://s3.amazonaws.com/{domain}/genesis-custom-blocks-pro/genesis-custom-blocks-pro.latest.zip?AWSAccessKeyId={key}&Signature={signature}%3D&Expires={timestamp}`

2020-08-27 03:56 UTC, kienstra commented
>BTW, the I did get a download link in the transient, but the download didn't work. The download link looked like...

Ah, I saw that too. I think the `download_link` was a dummy link, the actual plugin isn't deployed.

2020-08-27 03:57 UTC, kienstra commented
Thanks, really good suggestions! If it's alright, I'll apply them tomorrow.

2020-08-29 00:29 UTC, kienstra commented
Before submitting the sub key:

<img width="1057" alt="here-working-days" src="https://user-images.githubusercontent.com/4063887/91624235-aa37b380-e964-11ea-9303-561dd4489934.png">

After submitting the key:

<img width="1022" alt="here-after-submitting" src="https://user-images.githubusercontent.com/4063887/91624252-ccc9cc80-e964-11ea-8fbf-23019aa3b873.png">

2020-08-29 01:14 UTC, kienstra commented
Hi @lukecarbis,
Could you please review this? The [top comment](https://github.com/getblocklab/block-lab/pull/688#issue-473726400) is up to date.

I'll open a PR from `develop` to `add/full-migration` resolving merge conflicts. After that's merged, this PR will probably have merge conflicts that I'll resolve.

2020-08-31 00:55 UTC, lukecarbis approved these changes
Perfect @kienstra!! Nice work. Looks fantastic.

The download worked nicely too, now that the Pro version is available via that endpoint.

💜

2020-08-31 00:55 UTC, lukecarbis commented
Goodbye Block Lab… 😭

2020-08-31 01:17 UTC, kienstra commented
@lukecarbis, thanks for testing this!

2020-08-31 01:18 UTC, merged